version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/api/function-1/
      - npm install time
      - zip -r function-1.zip .
      - cd ..
      - export BUCKET=lambda-deployment-artifacts-1234567890123jvn
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - api/template.yml
    - api/outputtemplate.yml
  secondary-artifacts:
    artifact2:
      files:
        - api/function-1/function-1.zip
      name: function-1-lambda
    